# config.set('colors.webpage.prefers_color_scheme_dark', True)
# config.set('colors.webpage.darkmode.enabled', True)
config.set('colors.webpage.darkmode.threshold.background', 100)
# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html


# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://docs.google.com/*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'chrome-devtools://*')

# Load images automatically in web pages.
# Type: Bool
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications', False, 'https://www.reddit.com')

# Allow websites to show notifications.
# Type: BoolAsk
# Valid values:
#   - true
#   - false
#   - ask
config.set('content.notifications', False, 'https://www.youtube.com')

# Bindings for normal mode
config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')
config.bind('x', 'tab-close')
# config.bind(',u', 'spawn -d mpv-play --profile=fastyt {url}; close-tab')
# config.bind(',U', 'hint links spawn -d mpv-play --profile=fastyt {hint-url}')
# config.bind(';U', 'hint --rapid links spawn -d mpv-play --profile=fastyt {hint-url}')
# config.bind(';u', 'hint --rapid links spawn -d mpv-play --profile=fastyt {hint-url}')
config.bind(',u', 'spawn -d mpv-play {url}; close-tab')
config.bind(',U', 'hint links spawn -d mpv-play {hint-url}')
config.bind(';U', 'hint --rapid links spawn -d mpv-play {hint-url}')
config.bind(';u', 'hint --rapid links spawn -d mpv-play {hint-url};; clear-keychain ')
config.bind('<Alt+left>', 'back')
config.bind('<Alt+right>', 'forward')
config.unbind('D')
config.unbind('d')
config.bind('<Ctrl+Shift+r>', 'config-source')
config.set('input.insert_mode.auto_load', True)
config.bind('<Ctrl+k>', 'set-cmd-text -s :open ')
config.bind('<Ctrl+shift+k>', 'set-cmd-text -s :open -t ')
config.bind('<Ctrl+w>', 'tab-close', 'insert')
config.bind('<space>', 'scroll-page 0 0.9')
config.bind('<shift+space>', 'scroll-page 0 -0.9')
config.bind('<ctrl+tab>', 'tab-next')
config.bind('<ctrl+shift+tab>', 'tab-prev')

config.set('tabs.last_close', 'close')
config.set('session.default_name', 'defaultsession')
config.set('session.lazy_restore', True)
config.set('downloads.location.directory', '/tmp')

config.bind('ZQ', 'quit')
config.bind('ZZ', 'restart')

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

config.bind('<Ctrl+shift+d>', 
        'config-cycle colors.webpage.darkmode.enabled;;\
        config-cycle colors.webpage.prefers_color_scheme_dark;;\
        restart'
        )
config.bind('\\c', 'config-cycle colors.webpage.darkmode.enabled')
config.bind('\\v', 'config-cycle colors.webpage.prefers_color_scheme_dark')
